---
- hosts: webservers
  tasks:
    - name: login to jfrog
      shell: docker login -u siddesh -p Siddu@9880 shstechacademymay23.jfrog.io
    
    - name: pull an image
      shell: docker pull dhareppa.jfrog.io/artifactory/mydocker/devops_practice:{{ BUILD_NUMBER }}

    # - name: remove container
    #   shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 dhareppa.jfrog.io/artifactory/mydocker/devops_practice:{{ BUILD_NUMBER }}
 
   
